Kers/Controllers/Reports/ContactsController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Kers.Models.Repositories;
using Kers.Models.Entities.KERScore;
using Kers.Models.Entities.KERSmain;
using Kers.Models.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Kers.Models.Entities;
using Kers.Models.Contexts;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Distributed;
using Kers.Models.ViewModels;
using Microsoft.Extensions.Caching.Memory;
using Kers.Models.Data;

namespace Kers.Controllers.Reports
{

    [Route("reports/[controller]")]
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class ContactsController : Controller
    {
        KERScoreContext context;
        IFiscalYearRepository fiscalYearRepository;
        private IDistributedCache _cache;
        IActivityRepository activityRepo;
        IContactRepository contactRepo;
        const int workDaysPerYear = 228;
        public ContactsController(
                    KERScoreContext context,
                    IFiscalYearRepository fiscalYearRepository,
                    IDistributedCache _cache,
                    IActivityRepository activityRepo,
                    IContactRepository contactRepo
            )
        {
            this.context = context;
            this.fiscalYearRepository = fiscalYearRepository;
            this._cache = _cache;
            this.activityRepo = activityRepo;
            this.contactRepo = contactRepo;
        }
        [HttpGet]
        [Route("{fy?}")]
        public IActionResult Index(string fy = "0")
        {
            ViewData["fy"] = fy;
            return View();
        }
        [HttpGet]
        [Route("[action]/{fy?}")]
        public IActionResult State(string fy = "0")
        {
            ViewData["fy"] = fy;
            return View();
        }

        [HttpGet]
        [Route("[action]/{fy?}")]
        public async Task<IActionResult> StateAll(string fy = "0")
        {
            FiscalYear fiscalYear = GetFYByName(fy);

            if (fiscalYear == null)
            {
                //this.Log( fy ,"string", "Invalid Fiscal Year Idetifyer in Total By Month Snap Ed CSV Data Request.", "Reports", "Error");
                return new StatusCodeResult(500);
            }

            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;
            var table = await contactRepo.DataByEmployee(fiscalYear, 4, 0);
            return View(table);
        }


        [HttpGet]
        [Route("[action]/{type?}/{fy?}")]
        // type: 0 - all, 1 - UK, 2 - KSU
        public async Task<IActionResult> StateByMajorProgram(int type = 0, string fy = "0")
        {
            FiscalYear fiscalYear = GetFYByName(fy);
            if (fiscalYear == null)
            {
                return new StatusCodeResult(500);
            }
            var repoType = 4;




            if (type == 1)
            {
                repoType = 3;
                ViewData["Title"] = "UK ";
            }
            else if (type == 2)
            {
                repoType = 2;
                ViewData["Title"] = "KSU ";
            }
            var table = await contactRepo.DataByMajorProgram(fiscalYear, repoType);
            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;
            return View(table);
        }


        [HttpGet]
        [Route("[action]/{fy?}")]
        public async Task<IActionResult> ContactsByCountyByMajorProgram(string fy = "0")
        {

            FiscalYear fiscalYear = GetFYByName(fy);


            if (fiscalYear == null)
            {
                //this.Log( fy ,"string", "Invalid Fiscal Year Idetifyer in Total By Month Snap Ed CSV Data Request.", "Reports", "Error");
                return new StatusCodeResult(500);
            }
            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;
            var table = await activityRepo.ContactsByCountyByMajorProgram(fiscalYear);
            return View(table);
        }






        [HttpGet]
        [Route("[action]/{filter?}/{id?}/{fy?}", Name = "ContactsDataByMonthByMajorProgram")]
        public async Task<IActionResult> DataByMonthByMajorProgram(int filter = 1, int id = 0, string fy = "0")
        {
            // filter: 0 District, 1 Planning Unit, 2 KSU, 3 UK, 4 All
            FiscalYear fiscalYear = GetFYByName(fy);
            if (fiscalYear == null)
            {
                return new StatusCodeResult(500);
            }
            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;

            var fiscalYearSummaries = await contactRepo.GetPerPeriodSummaries(fiscalYear.Start, fiscalYear.End, filter, id);
            float[] SummariesArray = fiscalYearSummaries.ToArray();

            ViewData["totalHours"] = SummariesArray[0];
            ViewData["totalContacts"] = (int)SummariesArray[1];
            ViewData["totalMultistate"] = SummariesArray[2];
            ViewData["totalActivities"] = (int)SummariesArray[3];

            if (filter == 1)
            {
                ViewData["unit"] = context.PlanningUnit.Where(u => u.Id == id).FirstOrDefault();
                if (ViewData["unit"] == null)
                {
                    return new StatusCodeResult(500);
                }
            }
            else if (filter == 0)
            {
                ViewData["district"] = context.District.Where(u => u.Id == id).FirstOrDefault();
                if (ViewData["district"] == null)
                {
                    return new StatusCodeResult(500);
                }
            }
            else if (filter > 4)
            {
                return new StatusCodeResult(500);
            }


            List<List<PerGroupSummary>> result = await this.DataByMonth(fiscalYear, filter, 1, id);


            var output = new List<List<Kers.Models.Data.PerProgramActivities>>();

            var months = new List<string>();
            var hours = new List<string>();
            var runningDate = new DateTime(fiscalYear.Start.Year, fiscalYear.Start.Month, 28);


            foreach (var MonthResult in result)
            {
                var MonthData = new List<Kers.Models.Data.PerProgramActivities>();
                months.Add("'" + runningDate.ToString("MM/yyyy") + "'");
                runningDate = runningDate.AddMonths(1);
                hours.Add(MonthResult.Sum(s => s.Hours).ToString());
                foreach (var res in MonthResult)
                {
                    var ProgramActivities = new Kers.Models.Data.PerProgramActivities();
                    ProgramActivities.Audience = res.Audience;
                    ProgramActivities.Female = res.Female;
                    ProgramActivities.Hours = res.Hours;
                    ProgramActivities.MajorProgram = this.context.MajorProgram.Find(res.GroupId);
                    ProgramActivities.Male = res.Male;
                    ProgramActivities.Multistate = res.Multistate;
                    MonthData.Add(ProgramActivities);
                }
                output.Add(MonthData);
            }



            var monthsString = "[" + months.Aggregate((i, j) => i + "," + j) + "]";

            ViewData["months"] = monthsString;
            ViewData["hours"] = "[" + hours.Aggregate((i, j) => i + "," + j) + "]";





            var returnList = new List<Kers.Models.Data.PerProgramActivities>();

            var currentMonthNum = 0;

            var ProgramDataPerMonth = new List<ProgramDataPerMonth>();

            foreach (var month in output)
            {
                foreach (var program in month)
                {
                    var existingProgram = returnList.Where(r => r.MajorProgram == program.MajorProgram).FirstOrDefault();
                    if (existingProgram == null)
                    {

                        var programEntry = new ProgramDataPerMonth();
                        programEntry.MajorProgram = program.MajorProgram;
                        programEntry.Audience = new List<int>();
                        programEntry.Hours = new List<float>();
                        programEntry.Male = new List<int>();
                        programEntry.Female = new List<int>();
                        programEntry.Multistate = new List<float>();
                        for (var i = 0; i < currentMonthNum; i++)
                        {
                            programEntry.Audience.Add(0);
                            programEntry.Hours.Add(0);
                            programEntry.Male.Add(0);
                            programEntry.Female.Add(0);
                            programEntry.Multistate.Add(0);
                        }
                        programEntry.Audience.Add(program.Audience);
                        programEntry.Hours.Add(program.Hours);
                        programEntry.Male.Add(program.Male);
                        programEntry.Female.Add(program.Female);
                        programEntry.Multistate.Add(program.Multistate);

                        ProgramDataPerMonth.Add(programEntry);

                        existingProgram = new Kers.Models.Data.PerProgramActivities();
                        existingProgram.Audience = program.Audience;
                        existingProgram.Female = program.Female;
                        existingProgram.Hours = program.Hours;
                        existingProgram.MajorProgram = program.MajorProgram;
                        existingProgram.Male = program.Male;
                        existingProgram.Multistate = program.Multistate;

Kers/Controllers/Reports/MajorProgramController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Kers.Models.Repositories;
using Kers.Models.Entities.KERScore;
using Kers.Models.Entities.KERSmain;
using Kers.Models.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Kers.Models.Entities;
using Kers.Models.Contexts;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Distributed;
using Kers.Models.Data;
using Kers.Models.ViewModels;

namespace Kers.Controllers.Reports
{

    [Route("reports/[controller]")]
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class MajorProgramController : Controller
    {
        KERScoreContext context;
        IFiscalYearRepository fiscalYearRepository;
        IContactRepository contactRepo;
        IInitiativeRepository initiativeRepo;
        private FiscalYear currentFiscalYear;
        public MajorProgramController(
                    KERScoreContext context,
                    IFiscalYearRepository fiscalYearRepository,
                    IContactRepository contactRepo,
                    IInitiativeRepository initiativeRepo
            )
        {
            this.context = context;
            this.fiscalYearRepository = fiscalYearRepository;
            this.currentFiscalYear = this.fiscalYearRepository.currentFiscalYear("serviceLog");
            this.contactRepo = contactRepo;
            this.initiativeRepo = initiativeRepo;
        }



        [HttpGet]
        [Route("{fy?}")]
        public async Task<IActionResult> Index(string fy = "0")
        {
            FiscalYear fiscalYear = GetFYByName(fy);


            ViewData["fy"] = fiscalYear.Name;
            var initiatives = await context.StrategicInitiative.Where(i => i.FiscalYear == fiscalYear)
                                .Include(i => i.MajorPrograms)
                                .ToListAsync();


            return View(initiatives);
        }
        [HttpGet]
        [Route("program/{id}/{fy?}")]
        public async Task<IActionResult> Program(int id, string fy = "0")
        {
            var Program = await context.MajorProgram
                                .Where(m => m.Id == id)
                                .Include(m => m.StrategicInitiative).ThenInclude(i => i.FiscalYear)
                                .FirstOrDefaultAsync();
            if (Program != null)
            {


                ViewData["Indicators"] = await initiativeRepo.IndicatorSumPerMajorProgram(id);
                FiscalYear fiscalYear = Program.StrategicInitiative.FiscalYear;

                if (fy == "0")
                {
                    ViewData["fy"] = fiscalYear.Name;
                }
                else
                {

                    if (fy != fiscalYear.Name)
                    {
                        var toFY = GetFYByName(fy);
                        if (toFY != null)
                        {
                            var programWithTheSameName = await context.MajorProgram.Where(p => p.Name == Program.Name && p.StrategicInitiative.FiscalYear == toFY).FirstOrDefaultAsync();
                            if (programWithTheSameName != null)
                            {
                                return RedirectToAction("Program", new { id = programWithTheSameName.Id });
                            }
                            return RedirectToAction("Index", "Reports", new { fy = toFY.Name });
                        }
                        else
                        {
                            return RedirectToAction("Index", "Reports", new { fy = fy });
                        }
                    }
                }

                ViewData["FiscalYear"] = fiscalYear;
                ViewData["fy"] = fiscalYear.Name;
                var fiscalYearSummaries = await contactRepo.GetPerPeriodSummaries(fiscalYear.Start, fiscalYear.End, 5, id);
                float[] SummariesArray = fiscalYearSummaries.ToArray();

                ViewData["totalHours"] = SummariesArray[0];
                ViewData["totalContacts"] = (int)SummariesArray[1];
                ViewData["totalMultistate"] = SummariesArray[2];
                ViewData["totalActivities"] = (int)SummariesArray[3];


            }
            return View(Program);
        }

        public FiscalYear GetFYByName(string fy, string type = "serviceLog")
        {
            FiscalYear fiscalYear;
            if (fy == "0")
            {
                fiscalYear = this.fiscalYearRepository.currentFiscalYear(type);
            }
            else
            {
                fiscalYear = this.context.FiscalYear.Where(f => f.Name == fy && f.Type == type).FirstOrDefault();
            }
            return fiscalYear;
        }




    }
}

Kers/Controllers/Reports/ViewComonents/FeaturedPersonViewComponent.cs
using Kers.Models.Abstract;
using Kers.Models.Contexts;
using Kers.Models.Entities.KERScore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kers.Controllers.Reports.ViewComponents
{
    public class FeaturedPersonViewComponent : ViewComponent
    {
        private readonly KERScoreContext context;

        public FeaturedPersonViewComponent(KERScoreContext context){
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync( int PlanningUnitId = 0, FiscalYear fiscalYear = null ){
            

            var users = context.KersUser
                            .Where( u => u.RprtngProfile.enabled == true &&  u.PersonalProfile.Bio != null && u.PersonalProfile.Bio.Length > 100 && u.PersonalProfile.UploadImage != null);

            if( PlanningUnitId != 0 ){
                users = users.Where( u => u.RprtngProfile.PlanningUnitId == PlanningUnitId);
            }

            int total = users.Count();
            Random rndm = new Random();
            int offset = rndm.Next(0, total);

            users = users
                        .Include( u => u.PersonalProfile ).ThenInclude( p => p.UploadImage ).ThenInclude( i => i.UploadFile )
                        .Include( u => u.RprtngProfile).ThenInclude( r => r.PlanningUnit )
                        .Include( u => u.ExtensionPosition);

            var user = await users.Skip(offset).FirstOrDefaultAsync();

            ViewData["fy"] = fiscalYear == null ? "0" : fiscalYear.Name;

            return View(user);
        }
        
    }
}

Kers/Controllers/Reports/ViewComonents/LatestStoriesViewComponent.cs
using Kers.Models.Abstract;
using Kers.Models.Entities.KERScore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kers.Controllers.Reports.ViewComponents
{
    public class LatestStoriesViewComponent : ViewComponent
    {
        private readonly IStoryRepository storyRepo;

        public LatestStoriesViewComponent(IStoryRepository storyRepo)
        {
            this.storyRepo = storyRepo;
        }

        public async Task<IViewComponentResult> InvokeAsync( FiscalYear fiscalYear = null, int amount = 4, int PlanningUnitId = 0, int MajorProgramId = 0 )
        {
            var stories = await storyRepo.LastStories( fiscalYear, amount, PlanningUnitId, MajorProgramId );
            ViewData["PlanningUnitId"] = PlanningUnitId;
            ViewData["MajorProgramId"] = MajorProgramId;
            return View(stories);
        }
        
    }
}

Kers/Views/Reports/Counties.cshtml
@model List<Kers.Controllers.Reports.DistrictViewModel>

@{
    var FiscalYear = ViewData["FiscalYear"] as Kers.Models.Entities.KERScore.FiscalYear;
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Counties";
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";
    var index = 0;
    var divided = false;
}



<div class="row">
    <div class="col-md-6 col-sm-12">
        @foreach( var district in Model )
        {

            <div class="x_panel tile">
                <div class="x_title">
                  <h2>@district.District.Description Region</h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  
                        @foreach( var county in district.Counties)
                        {
                        <a asp-controller="Reports" 
   asp-action="County" asp-route-fy="@FiscalYear.Name" 
   asp-route-id="@county.Id" class="btn btn-default" style="margin-bottom: 10px;">@county.Name.Substring(0, county.Name.Length - 11)</a>
                        
                        }
                    
                </div>
              </div>
              @if( index >= (Model.Count() / 2) && !divided)
              {
                  divided = true;
                  @Html.Raw("</div><div class='col-md-6 col-sm-12'>")
              }
              index++;
        }
    </div>

</div>

Kers/Views/Reports/County.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    var FiscalYear = ViewData["FiscalYear"] as Kers.Models.Entities.KERScore.FiscalYear;
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";
    var conty = ViewData["County"] as Kers.Models.Entities.KERScore.PlanningUnit;
    ViewData["Title"] = conty.Name;
    var topPrograms = ViewData["TopPrograms"] as List<Kers.Models.ViewModels.ProgramDataViewModel>; 
    var topProgramsSum = ViewData["TopProgramsAudienceSum"] as int?;
    string[] colors = {"#BDC3C7", "#9B59B6", "#E74C3C",  "#26B99A", "#3498DB"};
    string colorsAsAString = "[\"#BDC3C7\", \"#9B59B6\", \"#E74C3C\",  \"#26B99A\", \"#3498DB\"]";
    var index = 0;
    var programNamesAsString = "[";
    var dataAsString = "[";
    foreach( var prgrm in topPrograms ){
      programNamesAsString += "\"" + prgrm.Program.Name + "\",";
      dataAsString += prgrm.DirectContacts.ToString() + ",";
    }
    programNamesAsString += "]";
    dataAsString += "]";

}
@await Html.PartialAsync("TopStatsFiscalYearPartial")
<ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
    <li role="presentation" class="active"><a asp-controller="Reports"  asp-action="County" asp-route-fy="@FiscalYear.Name" asp-route-id=@conty.Id>Summary</a>
    </li>
    <li role="presentation" class=""><a asp-controller="Contacts"  asp-action="DataByMonthByMajorProgram"  asp-route-fy="@FiscalYear.Name" asp-route-filter="1" asp-route-id=@conty.Id>Data by Major Program</a>
    </li>
    <li role="presentation" class=""><a asp-controller="Contacts"  asp-action="DataByMonthByEmployee" asp-route-fy="@FiscalYear.Name" asp-route-filter="1" asp-route-id=@conty.Id>Employee Contribution Data</a>
    </li>
</ul>
<div class="row">
  <div class="col-md-8 col-sm-8 col-xs-12">
    @await Component.InvokeAsync("MainStory", new {PlanningUnitId = conty.Id, FiscalYear = FiscalYear})
    <div class="row">
          <!-- Start to do list -->
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="panel">
              <div class="x_title">
                <h2>Major Programs <small></small></h2>
                
                <div class="clearfix"></div>
              </div>
              <div class="panel-body">

                <div class="">
                  <table class="" style="width:100%">
                  <tr>
                      <th style="width:37%;">
                      <p>Program Emphasis</p>
                      </th>
                      <th>
                      <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7">
                          <p class="">Name</p>
                      </div>
                      <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
                          <p class="">Percent</p>
                      </div>
                      </th>
                  </tr>
                  <tr>
                      <td>
                      <canvas class="canvasDoughnut" height="140" width="140" style="margin: 15px 10px 10px 0"></canvas>
                      </td>
                      <td>
                          <table class="tile_info">
                              <tbody>
                              @foreach(var progrm in topPrograms)
                              {
                                  <tr>
                                      <td style="font-size: 12px">
                                      <p><i class="fa fa-square" style="color: @colors[index];"></i>
                                      <a asp-controller="MajorProgram" 
                                    asp-action="Program" 
                                    asp-route-id="@progrm.Program.Id">
                                      @progrm.Program.Name.Substring(0,Math.Min(@progrm.Program.Name.Length, 19))...</a></p>
                                      </td>
                                      @{
                                      int percent = (int)Math.Round((double)(100 * progrm.DirectContacts) / (double)topProgramsSum);
                                      }
                                      <td style="font-size: 12px">@percent%</td>
                                  </tr>
                                  index++;
                              }
                              </tbody>
                              
                          </table>
                      </td>
                  </tr>
              </table>
                </div>
              </div>
            </div>
          </div>
          <!-- End to do list -->
          
          <!-- start of person widget -->
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="panel">
              <div class="x_title">
                <h2>People <small></small></h2>
                <div class="clearfix"></div>
              </div>
              <div class="panel-body">
                @await Component.InvokeAsync("FeaturedPerson", new {PlanningUnitId = conty.Id, FiscalYear = FiscalYear})
              </div>
            </div>

          </div>
          <!-- end of person widget -->
        </div>
        <div class="row">
          <div class="col-xs-12">
            <div class="panel">
              <div class="x_title">
                <h2>Reports <small></small></h2>
                <div class="clearfix"></div>
              </div>
              <div class="bs-glyphicons text-center">
                <ul class="bs-glyphicons-list">
                  <li>
                    <a asp-controller="PlansOfWork"  asp-action="PlansByCounty" asp-route-fy="@FiscalYear.Name" asp-route-id="@conty.Id">
                      <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
                      <span class="glyphicon-class">Plans of Work</span>
                    </a>
                  </li>
                  
                  <li>
                    <a asp-controller="Employees"  asp-action="Data" asp-route-fy="@FiscalYear.Name" asp-route-id="@conty.Id" asp-route-type="1">
                      <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                      <span class="glyphicon-class">Statistical Contacts</span>
                    </a>
                  </li>
                  <li>
                    <a asp-controller="Data"  asp-action="StoriesCounty" asp-route-fy="@FiscalYear.Name" asp-route-id="@conty.Id">
                      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                      <span class="glyphicon-class">Success Stories</span>
                    </a>
                  </li>
                  <li>
                    <a asp-controller="ProgramIndicators"  asp-action="Get" asp-route-fy="@FiscalYear.Name" asp-route-id="@conty.Id">
                      <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                      <span class="glyphicon-class">Program Indicators</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">




                      <section class="panel">

                        <div class="x_title">
                          <h2>About</h2>
                          <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                          <h3 class="green">@conty.Name</h3>

                          <p>@Html.Raw(conty.Description)</p>
                          <br>

                          <div class="project_detail">
                            @if(conty.Address != null && conty.Address != "")
                            {
                              <p class="title">Address:</p>
                              <p>@conty.FullName<br>
                              @conty.Address<br>
                              @conty.City, KY @conty.Zip</p>
                            }
                            <p class="title">Phone</p>
                            <p>@conty.Phone</p>
                            <p class="title">Email</p>
                            <p>@conty.Email</p>
                            <p class="title">Web Site</p>
                            <p><a href="@conty.WebSite" target="_blank">@conty.WebSite</a></p>
                            @if(conty.District != null)
                            {
                              <p class="title">District</p>
                              <p>@conty.District.Name - @conty.District.AreaName</p>
                              
                            }
                          </div>

                          <br>
                          <h5>County Population</h5>
                          <ul class="list-unstyled project_files">
                            <li><a href="">@conty.Population</a>
                            </li>
                            
                          </ul>
                          <br>

                         
                        </div>

                      </section>






          @await Component.InvokeAsync("LatestStories", new {PlanningUnitId = conty.Id, FiscalYear = FiscalYear})
      </div>
    </div>


    







  </div>     
  @section scripts
{
   <script type="text/javascript" src="@Url.Content("https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js")"></script>
   <script>
      
	 
		if ($('.canvasDoughnut').length){
			
      var chart_doughnut_settings = {
          type: 'doughnut',
          tooltipFillColor: "rgba(51, 51, 51, 0.55)",
          data: {
            labels: @Html.Raw(@programNamesAsString),
            datasets: [{
              data: @Html.Raw(@dataAsString),
              backgroundColor: @Html.Raw(@colorsAsAString),
              hoverBackgroundColor: [
                "#CFD4D8",
                "#B370CF",
                "#E95E4F",
                "#36CAAB",
                "#49A9EA"
              ]
            }]
          },
          options: { 
            legend: false, 
            responsive: false 
          }
        }
      
        $('.canvasDoughnut').each(function(){
          
          var chart_element = $(this);
          var chart_doughnut = new Chart( chart_element, chart_doughnut_settings);
          
        });			
      
      } 
    </script>
}

Kers/Views/Reports/Data.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Data";
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";
}