Kers/Controllers/Reports/ContactsController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Kers.Models.Repositories;
using Kers.Models.Entities.KERScore;
using Kers.Models.Entities.KERSmain;
using Kers.Models.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Kers.Models.Entities;
using Kers.Models.Contexts;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Distributed;
using Kers.Models.ViewModels;
using Microsoft.Extensions.Caching.Memory;
using Kers.Models.Data;

namespace Kers.Controllers.Reports
{

    [Route("reports/[controller]")]
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class ContactsController : Controller
    {
        KERScoreContext context;
        IFiscalYearRepository fiscalYearRepository;
        private IDistributedCache _cache;
        IActivityRepository activityRepo;
        IContactRepository contactRepo;
        const int workDaysPerYear = 228;
        public ContactsController(
                    KERScoreContext context,
                    IFiscalYearRepository fiscalYearRepository,
                    IDistributedCache _cache,
                    IActivityRepository activityRepo,
                    IContactRepository contactRepo
            )
        {
            this.context = context;
            this.fiscalYearRepository = fiscalYearRepository;
            this._cache = _cache;
            this.activityRepo = activityRepo;
            this.contactRepo = contactRepo;
        }
        [HttpGet]
        [Route("{fy?}")]
        public IActionResult Index(string fy = "0")
        {
            ViewData["fy"] = fy;
            return View();
        }
        [HttpGet]
        [Route("[action]/{fy?}")]
        public IActionResult State(string fy = "0")
        {
            ViewData["fy"] = fy;
            return View();
        }

        [HttpGet]
        [Route("[action]/{fy?}")]
        public async Task<IActionResult> StateAll(string fy = "0")
        {
            FiscalYear fiscalYear = GetFYByName(fy);

            if (fiscalYear == null)
            {
                //this.Log( fy ,"string", "Invalid Fiscal Year Idetifyer in Total By Month Snap Ed CSV Data Request.", "Reports", "Error");
                return new StatusCodeResult(500);
            }

            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;
            var table = await contactRepo.DataByEmployee(fiscalYear, 4, 0);
            return View(table);
        }


        [HttpGet]
        [Route("[action]/{type?}/{fy?}")]
        // type: 0 - all, 1 - UK, 2 - KSU
        public async Task<IActionResult> StateByMajorProgram(int type = 0, string fy = "0")
        {
            FiscalYear fiscalYear = GetFYByName(fy);
            if (fiscalYear == null)
            {
                return new StatusCodeResult(500);
            }
            var repoType = 4;




            if (type == 1)
            {
                repoType = 3;
                ViewData["Title"] = "UK ";
            }
            else if (type == 2)
            {
                repoType = 2;
                ViewData["Title"] = "KSU ";
            }
            var table = await contactRepo.DataByMajorProgram(fiscalYear, repoType);
            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;
            return View(table);
        }


        [HttpGet]
        [Route("[action]/{fy?}")]
        public async Task<IActionResult> ContactsByCountyByMajorProgram(string fy = "0")
        {

            FiscalYear fiscalYear = GetFYByName(fy);


            if (fiscalYear == null)
            {
                //this.Log( fy ,"string", "Invalid Fiscal Year Idetifyer in Total By Month Snap Ed CSV Data Request.", "Reports", "Error");
                return new StatusCodeResult(500);
            }
            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;
            var table = await activityRepo.ContactsByCountyByMajorProgram(fiscalYear);
            return View(table);
        }






        [HttpGet]
        [Route("[action]/{filter?}/{id?}/{fy?}", Name = "ContactsDataByMonthByMajorProgram")]
        public async Task<IActionResult> DataByMonthByMajorProgram(int filter = 1, int id = 0, string fy = "0")
        {
            // filter: 0 District, 1 Planning Unit, 2 KSU, 3 UK, 4 All
            FiscalYear fiscalYear = GetFYByName(fy);
            if (fiscalYear == null)
            {
                return new StatusCodeResult(500);
            }
            ViewData["FiscalYear"] = fiscalYear;
            ViewData["fy"] = fiscalYear.Name;

            var fiscalYearSummaries = await contactRepo.GetPerPeriodSummaries(fiscalYear.Start, fiscalYear.End, filter, id);
            float[] SummariesArray = fiscalYearSummaries.ToArray();

            ViewData["totalHours"] = SummariesArray[0];
            ViewData["totalContacts"] = (int)SummariesArray[1];
            ViewData["totalMultistate"] = SummariesArray[2];
            ViewData["totalActivities"] = (int)SummariesArray[3];

            if (filter == 1)
            {
                ViewData["unit"] = context.PlanningUnit.Where(u => u.Id == id).FirstOrDefault();
                if (ViewData["unit"] == null)
                {
                    return new StatusCodeResult(500);
                }
            }
            else if (filter == 0)
            {
                ViewData["district"] = context.District.Where(u => u.Id == id).FirstOrDefault();
                if (ViewData["district"] == null)
                {
                    return new StatusCodeResult(500);
                }
            }
            else if (filter > 4)
            {
                return new StatusCodeResult(500);
            }


            List<List<PerGroupSummary>> result = await this.DataByMonth(fiscalYear, filter, 1, id);


            var output = new List<List<Kers.Models.Data.PerProgramActivities>>();

            var months = new List<string>();
            var hours = new List<string>();
            var runningDate = new DateTime(fiscalYear.Start.Year, fiscalYear.Start.Month, 28);


            foreach (var MonthResult in result)
            {
                var MonthData = new List<Kers.Models.Data.PerProgramActivities>();
                months.Add("'" + runningDate.ToString("MM/yyyy") + "'");
                runningDate = runningDate.AddMonths(1);
                hours.Add(MonthResult.Sum(s => s.Hours).ToString());
                foreach (var res in MonthResult)
                {
                    var ProgramActivities = new Kers.Models.Data.PerProgramActivities();
                    ProgramActivities.Audience = res.Audience;
                    ProgramActivities.Female = res.Female;
                    ProgramActivities.Hours = res.Hours;
                    ProgramActivities.MajorProgram = this.context.MajorProgram.Find(res.GroupId);
                    ProgramActivities.Male = res.Male;
                    ProgramActivities.Multistate = res.Multistate;
                    MonthData.Add(ProgramActivities);
                }
                output.Add(MonthData);
            }



            var monthsString = "[" + months.Aggregate((i, j) => i + "," + j) + "]";

            ViewData["months"] = monthsString;
            ViewData["hours"] = "[" + hours.Aggregate((i, j) => i + "," + j) + "]";





            var returnList = new List<Kers.Models.Data.PerProgramActivities>();

            var currentMonthNum = 0;

            var ProgramDataPerMonth = new List<ProgramDataPerMonth>();

            foreach (var month in output)
            {
                foreach (var program in month)
                {
                    var existingProgram = returnList.Where(r => r.MajorProgram == program.MajorProgram).FirstOrDefault();
                    if (existingProgram == null)
                    {

                        var programEntry = new ProgramDataPerMonth();
                        programEntry.MajorProgram = program.MajorProgram;
                        programEntry.Audience = new List<int>();
                        programEntry.Hours = new List<float>();
                        programEntry.Male = new List<int>();
                        programEntry.Female = new List<int>();
                        programEntry.Multistate = new List<float>();
                        for (var i = 0; i < currentMonthNum; i++)
                        {
                            programEntry.Audience.Add(0);
                            programEntry.Hours.Add(0);
                            programEntry.Male.Add(0);
                            programEntry.Female.Add(0);
                            programEntry.Multistate.Add(0);
                        }
                        programEntry.Audience.Add(program.Audience);
                        programEntry.Hours.Add(program.Hours);
                        programEntry.Male.Add(program.Male);
                        programEntry.Female.Add(program.Female);
                        programEntry.Multistate.Add(program.Multistate);

                        ProgramDataPerMonth.Add(programEntry);

                        existingProgram = new Kers.Models.Data.PerProgramActivities();
                        existingProgram.Audience = program.Audience;
                        existingProgram.Female = program.Female;
                        existingProgram.Hours = program.Hours;
                        existingProgram.MajorProgram = program.MajorProgram;
                        existingProgram.Male = program.Male;
                        existingProgram.Multistate = program.Multistate;

Kers/Controllers/Reports/PeopleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Kers.Models.Repositories;
using Kers.Models.Entities.KERScore;
using Kers.Models.Entities.KERSmain;
using Kers.Models.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Kers.Models.Entities;
using Kers.Models.Contexts;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Distributed;
using Kers.Models.Data;
using Kers.Models.ViewModels;
using KersData.Models;

namespace Kers.Controllers.Reports
{

    [Route("reports/[controller]")]
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class PeopleController : Controller
    {
        KERScoreContext context;
        IKersUserRepository userRepo;
        IStoryRepository storyRepo;

        public PeopleController(
                    KERScoreContext context,
                    IKersUserRepository userRepo,
                    IStoryRepository storyRepo
            )
        {
            this.context = context;
            this.userRepo = userRepo;
            this.storyRepo = storyRepo;
        }



        [HttpGet]
        [Route("{fy?}", Name = "PeopleSearch")]
        public async Task<ActionResult> Index(
            string currentFilter,
            string searchString,
            int? page,
            string sortOrder = "alphabetically",
            int planningUnitId = 0,
            int extensionPositionId = 0,
            int length = 18,
            string fy = "0"
        )
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentLength"] = length;
            ViewData["Units"] = this.context.PlanningUnit.OrderBy(u => u.order).ToList();
            ViewData["Position"] = this.context.ExtensionPosition.OrderBy(u => u.order).ToList();

            ViewBag.CurrentUnit = planningUnitId;
            ViewBag.CurrentPosition = extensionPositionId;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var users = from s in context.KersUser
                        select s;
            users = users.Where(u => u.RprtngProfile.enabled);
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.PersonalProfile.LastName.Contains(searchString)
                                    || s.PersonalProfile.FirstName.Contains(searchString));
            }
            if (planningUnitId != 0)
            {
                users = users.Where(u => u.RprtngProfile.PlanningUnitId == planningUnitId);
            }
            if (extensionPositionId != 0)
            {
                users = users.Where(u => u.ExtensionPositionId == extensionPositionId);
            }

            switch (sortOrder)
            {

                case "position":
                    users = users.OrderBy(s => s.ExtensionPosition.Title);
                    break;
                case "unit":
                    users = users.OrderBy(s => s.RprtngProfile.PlanningUnit.Name);
                    break;
                default:
                    users = users.OrderBy(s => s.PersonalProfile.FirstName).ThenBy(s => s.PersonalProfile.LastName);
                    break;
            }

            int pageSize = length;
            users = users.Include(u => u.PersonalProfile).ThenInclude(p => p.UploadImage).ThenInclude(i => i.UploadFile)
                        .Include(u => u.RprtngProfile).ThenInclude(r => r.PlanningUnit)
                        .Include(u => u.ExtensionPosition);

            var list = await PaginatedList<KersUser>.CreateAsync(users.AsNoTracking(), page ?? 1, pageSize);
            ViewData["fy"] = fy;

            return View(list);
        }

        [HttpGet]
        [Route("person/{id}/{fy?}")]
        public async Task<ActionResult> Person(int id, string fy = "0")
        {
            var person = await context.KersUser.Where(u => u.Id == id)
                        .Include(u => u.ExtensionPosition)
                        .Include(u => u.Specialties).ThenInclude(s => s.Specialty)
                        .Include(u => u.RprtngProfile).ThenInclude(r => r.PlanningUnit)
                        .Include(u => u.PersonalProfile).ThenInclude(p => p.UploadImage).ThenInclude(i => i.UploadFile)
                        .Include(u => u.PersonalProfile).ThenInclude(p => p.Interests).ThenInclude(i => i.Interest)
                        .Include(u => u.PersonalProfile).ThenInclude(p => p.SocialConnections).ThenInclude(i => i.SocialConnectionType)
                        .AsNoTracking()
                        .FirstOrDefaultAsync();

            var stories = await this.storyRepo.LastStoriesByUser(person.Id);

            ViewData["stories"] = stories;
            ViewData["fy"] = fy;

            return View(person);
        }




    }
}

Kers/Views/Contacts/Areas.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "State Statistical Contact Reports";
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";
    var fy = ViewData["fy"] as string;
    if( fy == "0"){
      fy = "2018";
    }
}
@model List<Kers.Models.Entities.KERScore.ExtensionArea>


<div class="bs-glyphicons">
    <ul class="bs-glyphicons-list">
      <li>
        <a asp-controller="Contacts"  asp-action="Index" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          <span class="glyphicon-class">Back to State Reports</span>
        </a>
      </li>
        @if(Model != null){
            @foreach( var dstr in Model){
                <li>
                    <a asp-controller="Employees"  asp-action="Data" asp-route-type="7" asp-route-fy="@fy" asp-route-id=@dstr.Id>
                    <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                    <span class="glyphicon-class">@dstr.Name</span>
                    </a>
                </li>
            }
        }
      
      
    </ul>
<div class="clearfix"></div><br>
    <h2>FTEs by Major Program</h2>
    <ul class="bs-glyphicons-list">
        @if(Model != null){
            @foreach( var dstr in Model){
                <li>
                    <a asp-controller="ByProgram"  asp-action="Index" asp-route-type="7" asp-route-fy="@fy" asp-route-id=@dstr.Id>
                    <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                    <span class="glyphicon-class">@dstr.Name</span>
                    </a>
                </li>
            }
        }
      
      
    </ul>
  </div>

Kers/Views/Contacts/ContactsByCountyByMajorProgram.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Contacts by Major Program by County";
    ViewData["Subtitle"] = " Statistical Contact Reports";
}
@model Kers.Models.ViewModels.TableViewModel
<div class="text-right">
    <a asp-controller="Contacts"  asp-action="State" class="btn btn-default btn-xs">Back to State Reports</a><br>
</div>
@await Html.PartialAsync("TablePartial")

Kers/Views/Contacts/DataByMonthByEmployee.cshtml
@{
    var FiscalYear = ViewData["FiscalYear"] as Kers.Models.Entities.KERScore.FiscalYear;
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Statistical Contact Report for FY" + FiscalYear.Name;
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";

    var unit = ViewData["unit"] as Kers.Models.Entities.KERScore.PlanningUnit;
    var district = ViewData["district"] as Kers.Models.Entities.KERScore.District;


    var monthsForTheGraph = ViewData["months"] as string;
    var hoursForTheGraph = ViewData["hours"] as string;

    var colors = "[\"#72c380\", \"#6f7a8a\", \"#f7cb38\",\"#96CA59\", \"#3F97EB\", \"#5a8022\", \"#2c7282\"]";
    Random random = new Random();

    var personsForTheLegend = ViewData["personssForTheLegend"] as string;
    var ProgramsHoursGraphDataList = ViewData["PrersonsHoursGraphDataList"] as string;
    var ProgramsContactsByProgramSeries = ViewData["PersonsContactsByProgramSeries"] as string;

    

    var ProgramDataPerMonth = ViewData["PersonDataPerMonth"] as List<Kers.Controllers.Reports.PersonDataPerMonth>;
    var AllPersonssData = ViewData["AllPersonssData"] as List<Kers.Controllers.Reports.PersonDataPerMonth>;
    var ProgramsGendersGraphDataList = ViewData["ProgramsGendersGraphDataList"] as string;


    var GraphCategories = ViewData["GraphCategories"] as string;
    var GraphData = ViewData["GraphData"] as string;
    var GraphLinks = ViewData["GraphLinks"] as string;

    var people = ViewData["people"] as string;
    var hours = ViewData["hours"] as string;
    var contacts = ViewData["contacts"] as string;



}
@model Kers.Models.ViewModels.TableViewModel

@if( unit != null )
{
    <h3>@unit.Name <small>@FiscalYear.Start.ToString("MMM d, yyyy") - @FiscalYear.End.ToString("MMM d, yyyy")</small></h3>
    
}
else if( district != null)
{
    <h3>@district.Name <small>@FiscalYear.Start.ToString("MMM d, yyyy") - @FiscalYear.End.ToString("MMM d, yyyy")</small></h3>
}

<style>
    .main-container .graph{
        height: 380px;
    }
    .overlay .main-container .graph{
        height: 560px;
    }
    .main-container{
        height: 430px;
    }
    .tile{
        cursor:pointer !important;
        width: 33%;
    }
    .tiles .graph{
        height: 190px;
        margin-top: -40px;
        margin-left: -10px;
    }
    ul.top_profiles{
        height: auto;
    }
    .overlay {
        position: fixed;
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        background: rgba(255, 255, 255, 0.9);
        z-index: 10;
    }
    .resize{
        position: absolute;
        top: 10px; 
        right: 10px; 
        width:30px;
        height:30px;
        font-size: 24px; 
        cursor:pointer;
    }

</style>
@await Html.PartialAsync("TopStatsFiscalYearPartial")

<ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
    <li role="presentation" class=""><a asp-controller="Reports"  asp-action="County" asp-route-fy="@FiscalYear.Name" asp-route-id=@unit.Id>Summary</a>
    </li>
    <li role="presentation" class=""><a asp-controller="Contacts"  asp-action="DataByMonthByMajorProgram" asp-route-fy="@FiscalYear.Name" asp-route-filter="1" asp-route-id=@unit.Id>Data by Major Program</a>
    </li>
    <li role="presentation" class="active"><a asp-controller="Contacts"  asp-action="DataByMonthByEmployee" asp-route-fy="@FiscalYear.Name" asp-route-filter="1" asp-route-id=@unit.Id>Employee Contribution Data</a>
    </li>
</ul>


<div class="row">
    <div class="col-md-12">
        <div class="panel">
                <div class="x_title">
                    <h2>Statistical Contacts by Employee</h2>
                    
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="main-content" class="col-md-9 col-sm-12 col-xs-12">
                        <div id="resize-full" class="resize"><span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span></div>
                        <div id="resize-small" class="resize" style="display:none;"><span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span></div>
                        
                    <div class="main-container">
                        <div id="Chart0" class="demo-placeholder">
                            <span>Male, Female Distribution</span>
                            <h2>Per Employee</h2>
                            <div class="graph"></div>
                        </div>
                    </div>
                    <div class="tiles">
                        <div class="col-md-4 tile">
                            <div id="Chart1">
                                <span>Employees</span>
                                <h2>Contacts per Month</h2>
                                <div class="graph"></div>
                            </div>
                        </div>
                        <div  class="col-md-4 tile">
                            <div id="Chart2">
                                <span>Contacts and Hours per Employee</span>
                                <h2>Comparison</h2>
                                <div class="graph"></div>
                            </div>
                        </div>
                        <div  class="col-md-4 tile">
                            <div id="Chart3">
                                <span>Employees </span>
                                <h2>Hours per Month</h2>
                                <div class="graph"></div>
                            </div>
                        </div>
                    </div>

                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12">
                    <div>
                        <div class="x_title">
                        <h2>County Extension Staff</h2>
                        
                        <div class="clearfix"></div>
                        </div>
                        <ul class="list-unstyled top_profiles scroll-view">

                        @foreach( var prgrmData in AllPersonssData )
                        {
                            <li class="media event">
                            <div class="media-body">
                                <a class="title" asp-controller="People"  asp-action="Person" asp-route-id=@prgrmData.KersUser.Id>@prgrmData.KersUser.PersonalProfile.FirstName @prgrmData.KersUser.PersonalProfile.LastName</a>
                                <p><strong>@prgrmData.Audience.Sum(s => s)</strong> Contacts (@prgrmData.Male.Sum(s => s) Male, @prgrmData.Female.Sum(s => s) Female)</p>
                                <p> <small>@prgrmData.Hours.Sum(s => s) Hours</small>
                                </p>
                            </div>
                            </li>
                        }
                        
                        </ul>
                    </div>
                    </div>
                </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="x_title">
                <h2>Statistical Contacts Data</h2>
                
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
            @await Html.PartialAsync("TablePartial")
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>



@section scripts
{
   <script type="text/javascript" src="@Url.Content("https://cdnjs.cloudflare.com/ajax/libs/echarts/4.1.0/echarts-en.min.js")"></script>
   <script>
      
	

    var options = [];
    var charts = [];
    var chartPlaceholders = ["Chart0","Chart1","Chart2", "Chart3"];
    
    options[0] = {
        tooltip: {
            axisPointer: {
                type: 'shadow'
            },
            formatter: function (params, ticket, callback) {
                return params.data[2] + '<br>Female: ' + params.data[0] + ', Male: ' + params.data[1];
            }
        },
        color: @Html.Raw(colors),
        xAxis: {
        name: "Female",
        nameLocation: "center",
        nameGap: 22
        },
        yAxis: {
        name: "Male",
        nameLocation: "center",
        nameGap: 22
        },
        series: [{
            symbolSize: 20,
            data: @Html.Raw(ProgramsGendersGraphDataList),
            itemStyle: {
            color: function (params) {
                var colors = @Html.Raw(colors);
                return colors[Math.floor(Math.random() * colors.length)];
            }
            } ,
            type: 'scatter'
        }]
    };


    options[1] = {
        color: @Html.Raw(colors),
        legend: {
            type: 'scroll',
            data: @Html.Raw(people)
        },
        toolbox: {
            show: !1
        },
        calculable: !1,
        tooltip : {
            trigger: 'axis',
            axisPointer : {            
                type : 'shadow'        
            }
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                data : @Html.Raw(monthsForTheGraph),
                axisTick: {
                    alignWithLabel: true
                }
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : @Html.Raw(ProgramsContactsByProgramSeries)
    };

    var GraphCategories = [{ name: "Employees"}, { name: "Major Programs"}, { name: "Success Stories"}];

    options[2] = {
        color: @Html.Raw(colors),
        tooltip: {
            trigger: 'item',
            formatter: "{a} <br/>{b}: {c} ({d}%)"
        },
        legend: {
            orient: 'vertical',
            x: 'left',
            data: @Html.Raw(people)
        },
        series: [
            {
                name:'Hours',
                type:'pie',
                label: {
                    show: false
                },
                radius: [0, '30%'],
                data:[@Html.Raw(hours)]
            },
            {
                name:'Contacts',
                type:'pie',
                radius: ['40%', '55%'],
                data:[@Html.Raw(contacts)]
            }
        ]
    };
    
    

        options[3] = {
                tooltip: {
                    trigger: "axis"
                },
                legend: {
                    x: 220,
                    y: 40,
                    data: @Html.Raw(people)
                },
                calculable: !6,
                xAxis : [
                    {
                        type : 'category',
                        data : @Html.Raw(monthsForTheGraph),
                        boundaryGap: !1
                    }
                ],
                yAxis : [
                    {
                        type : 'value'
                    }
                ],
                series: @Html.Raw(ProgramsHoursGraphDataList)
            };
        $( document ).ready(function() {
            initCharts();
        });
        $(window).on('resize', function(){
            resizeCharts();
        });


        function initCharts(){
            var theId = $("#main");
            for( i = 0; i < 4; i++)
            {
                charts[i] = echarts.init($("#" + chartPlaceholders[i] + " .graph")[0]);
                if( i > 0) {
                    if( options[i].legend != null && options[i].legend != undefined ){
                        options[i].legend.show = false;
                    }
                }
                charts[i].setOption(options[i]);
            }
        }
        function resizeCharts(){
            for( i = 0; i < 4; i++)
            {
                if(charts[i] != null && charts[i] != undefined){
                    charts[i].resize();
                }
            }
        }




        $(".tile").click( function(){
            var current = $( ".main-container" ).children().first();
            var currentIndex = +current.attr('id').slice(-1);
            if(options[currentIndex].legend != null && options[currentIndex].legend != undefined){
                options[currentIndex].legend.show = false;
                charts[currentIndex].setOption(options[currentIndex]);  
            }
            var clicked = $(this).children().first();
            var clickedIndex = +clicked.attr('id').slice(-1);
            if(options[clickedIndex].legend != null && options[clickedIndex].legend != undefined){
                options[clickedIndex].legend.show = true;
                charts[clickedIndex].setOption(options[clickedIndex]);
            }
            $( ".main-container" ).append( clicked );
            $(this).append(current);
            resizeCharts()
        })

        $('#resize-full').click(function(){
            $(".main-container").height(560);
            $(this).hide();
            $('#resize-small').show();
            $( "#main-content" ).addClass( "overlay" );
            resizeCharts();
        });
        $('#resize-small').click(function(){
            $(".main-container").height(430);
            $(this).hide();
            $('#resize-full').show();
            $( "#main-content" ).removeClass( "overlay" );
            resizeCharts();
        });













    </script>
}

Kers/Views/Contacts/Indicators.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Program Indicators Reports";
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";
}
@model Kers.Models.ViewModels.TableViewModel

@await Html.PartialAsync("TablePartial")

Kers/Views/Contacts/StateAll.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    var FiscalYear = ViewData["FiscalYear"] as Kers.Models.Entities.KERScore.FiscalYear;
    ViewData["Title"] = "All Statistical Contacts for FY" + FiscalYear.Name;
    ViewData["Subtitle"] = FiscalYear.Start.ToString("MMM d, yyyy") + " - " + FiscalYear.End.ToString("MMM d, yyyy");
}
@model Kers.Models.ViewModels.TableViewModel
<div class="text-right">
    <a asp-controller="Contacts"  asp-action="State" class="btn btn-default btn-xs">Back to State Reports</a><br>
</div>
@await Html.PartialAsync("TablePartial")