Kers/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Kers.Models.Repositories;
using Kers.Models.Entities.KERScore;
using Kers.Models.Entities.KERSmain;
using Kers.Models.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Kers.Models.Entities;
using Kers.Models.Contexts;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using System.Text.RegularExpressions;

namespace Kers.Controllers
{

    [Route("api/[controller]")]
    public class StoryController : Controller
    {
        KERScoreContext context;
        KERSmainContext mainContext;
        IKersUserRepository userRepo;
        IStoryRepository storyRepo;
        ILogRepository logRepo;
        IFiscalYearRepository fiscalYearRepo;

        private int DefaultNumberOfItems = 10;
        public StoryController( 
                    KERSmainContext mainContext,
                    KERScoreContext context,
                    IKersUserRepository userRepo,
                    ILogRepository logRepo,
                    IFiscalYearRepository fiscalYearRepo,
                    IStoryRepository storyRepo
            ){
           this.context = context;
           this.mainContext = mainContext;
           this.userRepo = userRepo;
           this.logRepo = logRepo;
           this.fiscalYearRepo = fiscalYearRepo;
           this.storyRepo = storyRepo;
        }


        [HttpGet("numb")]
        [Authorize]
        public IActionResult GetNumb(){
            
            var numStories = context.Story.
                                Where(e=>e.KersUser == this.CurrentUser());
            
            return new OkObjectResult(numStories.Count());
        }

        [HttpGet("id/{id}")]
        [Authorize]
        public IActionResult ById(int id){
            
            var story = context.StoryRevision.
                                Include(s => s.MajorProgram).
                                Where(e=>e.Id == id).
                                FirstOrDefault();
            return new OkObjectResult(story);
            
            
        }

        [HttpGet("latest/{skip?}/{amount?}")]
        [Authorize]
        public IActionResult Get(int skip = 0, int amount = 10){
            
            var lastStories = context.Story.
                                Where(e=>e.KersUser == this.CurrentUser()).
                                Include(s => s.Revisions).ThenInclude(r => r.StoryImages).
                                Include( s => s.Revisions).ThenInclude( r => r.MajorProgram ).ThenInclude( p => p.StrategicInitiative ).ThenInclude( i => i.FiscalYear ).
                                Include( s => s.Revisions).ThenInclude( r => r.StoryAudienceConnections).ThenInclude( a => a.StoryAudienceType).
                                OrderByDescending(e=>e.Updated).
                                Skip(skip).
                                Take(amount);
            
            var revs = new List<StoryRevision>();
            if(lastStories != null){
                foreach(var story in lastStories){
                    revs.Add( story.Revisions.OrderBy(r=>r.Created).Last() );
                }
            }
            return new OkObjectResult(revs);
        }


        [HttpGet("author/{storyid}")]
        [Authorize]
        public IActionResult Author(int storyid){
            
            var rev = context.StoryRevision.
                                Where(e=>e.Id == storyid).
                                FirstOrDefault();
            
            if(rev==null){
                return new OkObjectResult(null);
            }else{
                var story = context.Story.
                            Where(s => s.Id == rev.StoryId).
                            Include(s => s.KersUser).ThenInclude(u => u.PersonalProfile).
                            Include(s => s.KersUser).ThenInclude(u => u.RprtngProfile).ThenInclude(p => p.PlanningUnit).
                            FirstOrDefault();
                if(story == null){
                    return null;
                }else{
                    return new OkObjectResult(story.KersUser);
                }

            }
            
        }

        [HttpGet("latestbyuser/{userid}/{amount?}/{fy?}")]
        [Authorize]
        public IActionResult LatestByUser(int userid, int amount = 10, string fy = "0"){


            FiscalYear fiscalYear;
            if(fy != "0"){
                fiscalYear = fiscalYearRepo.byName(fy, FiscalYearType.ServiceLog);
            }else{
                fiscalYear = fiscalYearRepo.currentFiscalYear(FiscalYearType.ServiceLog);
            }


            
            var lastStories = context.Story.
                                Where(e=>e.KersUser.Id == userid && e.MajorProgram.StrategicInitiative.FiscalYear == fiscalYear).
                                Include(s => s.Revisions).ThenInclude(r => r.StoryImages).ThenInclude(i => i.UploadImage).ThenInclude(f => f.UploadFile).
                                Include( s => s.Revisions).ThenInclude( r => r.MajorProgram ).ThenInclude( p => p.StrategicInitiative ).ThenInclude( i => i.FiscalYear ).
                                Include( s => s.Revisions).ThenInclude( r => r.StoryAudienceConnections).
                                Take(amount).
                                OrderByDescending(e=>e.Updated);
            
            var revs = new List<StoryRevision>();
            if(lastStories != null){
                foreach(var story in lastStories){
                    var last = story.Revisions.OrderBy(r=>r.Created).Last();
                    if( last.MajorProgram.StrategicInitiative.FiscalYear.Id == fiscalYear.Id){
                        revs.Add( last );
                    }
                    if( revs.Count >= amount ) break;
                }
            }
            foreach(var rev in revs){
                foreach( var img in rev.StoryImages){
                    img.UploadImage.UploadFile.Content = null;
                }
            }
            return new OkObjectResult(revs);
        }



        [HttpGet("perDay/{userid}/{start}/{end}")]
        [Authorize]
        public IActionResult PerDay(int userid, DateTime start, DateTime end ){
            
            end = end.AddDays(1);
            var filteredStories = context.Story.
                                Where(a=>a.KersUser.Id == userid & a.Updated > start & a.Updated < end).ToList();
            var numPerDay = filteredStories.
                                GroupBy(e => new {
                                    Date = e.Updated.Day
                                }).
                                Select(c => new {
                                    Day = c.FirstOrDefault().Updated.ToString("yyyy-MM-dd"),
                                    Count = c.Count()
                                }).
                                OrderByDescending(e => e.Day);
            return new OkObjectResult(numPerDay);
        }


        [HttpGet("GetCustom")]
        public IActionResult GetCustom( [FromQuery] string search, 
                                        [FromQuery] string unit = "0", 
                                        [FromQuery] string amount = "0",
                                        [FromQuery] string program = "0",
                                        [FromQuery] string snap = "0",
                                        [FromQuery] string withImage = "0",
                                        [FromQuery] string fiscalYear = "0"
                                        ){
            var theAmount = Convert.ToInt32(amount);
            theAmount =  theAmount <= 0 ? DefaultNumberOfItems : theAmount ;
            var Fy = 
                    fiscalYear == "0"
                    ?
                    this.fiscalYearRepo.currentFiscalYear(FiscalYearType.ServiceLog)
                    :
                    this.fiscalYearRepo.byName(fiscalYear, FiscalYearType.ServiceLog);
            if(Fy == null) this.fiscalYearRepo.currentFiscalYear(FiscalYearType.ServiceLog);

            IEnumerable<StoryRevision> revs = storyRepo.LastStoryRevisions(Fy);
            if(search != null){
                revs = revs.Where( i => i.Title.Contains(search) || i.Story.Contains(search));
            }
            if( program != "0"){
                revs = revs.Where( i => i.MajorProgramId == Convert.ToInt32(program) );
            }
            if( snap != "0"){
                revs = revs.Where( i => i.IsSnap );
            }
            if( withImage != "0"){
                revs = revs.Where( i => i.StoryImages.Count() > 0 );
            }
            
            if( unit != "0" ){
                var i = 0;
                var newRevs = new List<StoryRevision>();
                foreach( var rev in revs ){
                    var story = context.Story.Where(s => rev.StoryId == s.Id)
                                        .Include(s => s.KersUser).ThenInclude( u => u.RprtngProfile)
                                        .FirstOrDefault();
                    if( story != null ){
                        if(story.KersUser.RprtngProfile.PlanningUnitId == Convert.ToInt32(unit)){
                            i++;
                            newRevs.Add(rev);
                        }
                    }
                    if( i >= theAmount ) break;
                }
                revs = newRevs;
            }
            revs = revs.Take(theAmount);
            foreach(var rev in revs){
                var imgs = new List<StoryImage>();
                foreach( var img in rev.StoryImages){

Kers/Views/Data/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Data";
    ViewData["Subtitle"] = "Kentucky Extension Reporting System";
    var fy = ViewData["fy"] as string;
    if( fy == "0"){
      fy = "2018";
    }
}
<br><br>
<div class="bs-glyphicons">
    <ul class="bs-glyphicons-list">
      <li>
        <a asp-controller="PlansOfWork"  asp-action="Countylist" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
          <span class="glyphicon-class">Plans of Work - by Planning Unit</span>
        </a>
      </li>
      <li>
        <a asp-controller="PlansOfWork"  asp-action="Programlist" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
          <span class="glyphicon-class">Plans of Work by Major Program</span>
        </a>
      </li>
      <li>
        <a asp-controller="Contacts"  asp-action="Index" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
          <span class="glyphicon-class">Statistical Contact Summaries</span>
        </a>
      </li>
      <li>
        <a asp-controller="Data"  asp-action="StoriesCounty"   asp-route-fy="@fy">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <span class="glyphicon-class">Success Stories by Planning Unit</span>
        </a>
      </li>
      <li>
        <a asp-controller="Reports"  asp-action="AffirmativeAction" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <span class="glyphicon-class">Affirmative Action Reports</span>
        </a>
      </li>
      <li>
        <a asp-controller="Data"  asp-action="StoriesProgram" asp-route-id=0  asp-route-fy="@fy">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <span class="glyphicon-class">Success Stories by Major Program</span>
        </a>
      </li>
      <li>
        <a asp-controller="ProgramIndicators"  asp-action="Countylist" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
          <span class="glyphicon-class">Program Indicators</span>
        </a>
      </li>
      <li>
        <a asp-action="Ksu" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
          <span class="glyphicon-class">Kentucky State University</span>
        </a>
      </li>
      <li>
        <a href="https://kers.ca.uky.edu/CES/rpt/CESreports.aspx">
          <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
          <span class="glyphicon-class">Reports for Previous Years</span>
        </a>
      </li>
      
      

      

    </ul>
  </div>

Kers/Views/Data/Ksu.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    ViewData["Title"] = "Kentucky State University Reports";
    var fy = ViewData["fy"];
}

<br><br>
<div class="bs-glyphicons">
    <ul class="bs-glyphicons-list">
      <li>
        <a asp-controller="Data"  asp-action="Index" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          <span class="glyphicon-class">Back to Data</span>
        </a>
      </li>
      <li>
        <a asp-controller="Story"  asp-action="Ksu" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
          <span class="glyphicon-class">Susccess Stories</span>
        </a>
      </li>
      <li>
        <a asp-controller="ProgramIndicators"  asp-action="Ksu" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
          <span class="glyphicon-class">Program Indicators by Major Program</span>
        </a>
      </li>
      <li>
        <a asp-controller="ProgramIndicators"  asp-action="ByPersonKSU" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
          <span class="glyphicon-class">Program Indicators by Employee</span>
        </a>
      </li>
      <li>
        <a asp-controller="Employees"  asp-action="Data" asp-route-type="2" asp-route-id="0" asp-route-fy="@fy">
          <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
          <span class="glyphicon-class">Statistical Contacts</span>
        </a>
      </li>
    </ul>
  </div>


<br><br>

Kers/Views/Data/StoriesCounty.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    var FiscalYear = ViewData["FiscalYear"] as Kers.Models.Entities.KERScore.FiscalYear;
    ViewData["Title"] = "Success Stories By Planning Unit FY"+FiscalYear.Name;
    ViewData["Subtitle"] = FiscalYear.Start.ToString("MMM d, yyyy") + " - " + FiscalYear.End.ToString("MMM d, yyyy");
}
@model Kers.Models.ViewModels.UnitStoryViewModel

<br><br>
<div class="row">
    <label class="col-md-2">Select Planning Unit</label>
    <div class="col-md-8">
        <select asp-for="PlanningUnit.Id" asp-items="@(new SelectList(Model.PlanningUnits,"Id","Name"))" class="form-control" onchange="location = '@Url.RouteUrl("StoryCounty", new { id = "" })' + '/' + this.value;">
            <option>-- select --</option>
        </select>
    </div>
</div><br><br>

@await Html.PartialAsync("StoriesList", Model.Stories)

<br><br>

Kers/Views/Data/StoriesProgram.cshtml
@{
    Layout = "~/Views/Shared/_LayoutReports.cshtml";
    var FiscalYear = ViewData["FiscalYear"] as Kers.Models.Entities.KERScore.FiscalYear;
    ViewData["fy"] = FiscalYear.Name;
    ViewData["Title"] = "Success Stories By MajorProgram FY"+FiscalYear.Name;
    ViewData["Subtitle"] = FiscalYear.Start.ToString("MMM d, yyyy") + " - " + FiscalYear.End.ToString("MMM d, yyyy");
}
@model Kers.Models.ViewModels.ProgramStoryViewModel

<br><br>
<div class="row">
    <label class="col-md-2">Select Major Program</label>
    <div class="col-md-8">
        <select asp-for="MajorProgram.Id" asp-items="@(new SelectList(Model.MajorPrograms,"Id","Name"))" class="form-control" onchange="location = '@Url.RouteUrl("StoryProgram", new { id = "", })' + '/' + this.value;">
            <option>-- select --</option>
        </select>
    </div>
</div><br><br>

@await Html.PartialAsync("StoriesList", Model.Stories)


<br><br>